apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bookings.fullname" . }}
  labels:
    app: {{ template "bookings.name" . }}
    project: {{ .Values.project }}
    component: {{ .Values.component }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ template "bookings.name" . }}
      project: {{ .Values.project }}
      component: {{ .Values.component }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bookings.name" . }}
        project: {{ .Values.project }}
        component: {{ .Values.component }}
        release: {{ .Release.Name }}
    spec:
 {{- if .Values.image.pullSecret.enabled }}
      imagePullSecrets:
      - name: {{ template "bookings.fullname" . }}-docker
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.pullSecret.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: CINEMA_BOOKINGS
            value: {{ .Values.container.host }}:{{ .Values.service.port }}
        {{- range $key, $value := .Values.environmentVariables }}
          - name: {{ $key }}
            value: {{ $value | quote }}
        {{- end }}      
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.service.port }}